# Сборка фронтенда
FROM node:18 AS build
WORKDIR /app
COPY package.json ./
RUN npm set registry https://registry.npmmirror.com/ && npm install --include=dev
# RUN npm install --include=dev
COPY . .
RUN npm run build

# Контейнер Nginx с готовыми файлами
FROM nginx:latest
COPY nginx/conf.d/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
