version: '3.8'

services:

  app:
    image: andrey122333/sub-server:dev
    environment:
      - MONGO_URI=mongodb://admin:password@mongo:27017/subscriptions?authSource=admin
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo  # Зависимость от MongoDB

  app-test:
    image: andrey122333/sub-server:test
    environment:
      - NODE_ENV=test
      - MONGO_URI=mongodb://admin:password@mongo-test:27017/subscriptions_test?authSource=admin
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo-test


  
  nginx:
    image: nginx:latest
    environment:
      API_BACKEND_URL: http://app:4000  # Для docker-сети
    volumes:
      - ./client/dist:/var/www/html  # Собранный 
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  mongo-test:
    image: mongo:6.0
    ports:
      - "27038:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_test_data:/data/db



  client-builder:
    image: andrey122333/sub-client:build
    command: npm run build
    container_name: devops_client_build
    volumes:
      - ./client/dist:/app/dist  # Экспорт собранных файлов


  client-test:
    image: andrey122333/sub-client:test
    command: npm run test



volumes:
  mongodb_data:
  mongodb_test_data:
