apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'app'
        static_configs:
          - targets: ['app:4000']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
      - job_name: 'cadvisor'
        scheme: https
        tls_config:
          insecure_skip_verify: true
        authorization:
          credentials_file: '/var/run/secrets/kubernetes.io/serviceaccount/token'
        static_configs:
          - targets: ['minikube:10250']
        metrics_path: /metrics/cadvisor
