name: CI/CD with Docker

on:
  push:
    branches: ["laba2"]
  pull_request:
    branches: ["laba2"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Pull images from Docker Hub
        run: |
         docker pull andrey122333/sub-server:dev
         docker pull andrey122333/sub-server:test
         docker pull andrey122333/sub-client:build
         docker pull andrey122333/sub-client:test


  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      mongo-test:
        image: mongo:6.0
        ports:
          - "27018:27017"
        env:
          MONGO_INITDB_ROOT_rootNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run tests inside containers
        run: |
          docker compose -f docker-compose.yml up app-test mongo-test  --abort-on-container-exit --exit-code-from app-test
