name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - newLaba3
  pull_request:
    branches:
      - newLaba3

env:
  DOCKER_HUB_REPO: andrey122333
  IMAGE_NAME_BACKEND: sub-server:dev
  IMAGE_NAME_FRONTEND: sub-nginx:latest
  IMAGE_NAME_FRONTEND_TEST: sub-client:test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Сборка бэкенд образа (для разработки)
      - name: Build backend image
        run: |
          cd server
          docker build -t $DOCKER_HUB_REPO/$IMAGE_NAME_BACKEND -f Dockerfile .

      # Сборка фронтенд образа (продакшн)
      - name: Build frontend production image
        run: |
          cd client
          docker build -t $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND -f Dockerfile.nginx .

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Тесты бэкенда (используем уже собранный образ)
      - name: Run backend tests
        run: |
          docker run --rm $DOCKER_HUB_REPO/$IMAGE_NAME_BACKEND npm test

      # Сборка и запуск тестов для фронтенда
      - name: Build frontend test image
        run: |
          cd client
          docker build -t $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND_TEST -f Dockerfile.test .

      - name: Run frontend tests
        run: |
          docker run --rm $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND_TEST

  push:
    needs: [build, test]
    # Push только при пуше в ветку, не при pull request
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Push бэкенд образа
      - name: Push backend image
        run: |
          docker push $DOCKER_HUB_REPO/$IMAGE_NAME_BACKEND

      # Push фронтенд образа
      - name: Push frontend image
        run: |
          docker push $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND