name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - newLaba3
  pull_request:
    branches:
      - newLaba3

env:
  DOCKER_HUB_REPO: andrey122333
  IMAGE_NAME_BACKEND: sub-server:dev
  IMAGE_NAME_FRONTEND: sub-nginx:latest
  IMAGE_NAME_FRONTEND_TEST: sub-client:test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Сборка бэкенд образа
      - name: Build backend image
        run: |
          cd server
          docker build \
            --target dev \
            -t $DOCKER_HUB_REPO/$IMAGE_NAME_BACKEND \
            .

      # Сборка фронтенд образа
      - name: Build frontend production image
        run: |
          cd client
          docker build \
            -t $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND \
            -f Dockerfile.nginx \
            .

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Запуск тестовой MongoDB для бэкенда
      - name: Start MongoDB for backend tests
        run: |
          docker run -d --name mongo-test \
            -p 27038:27017 \
            -e MONGO_INITDB_ROOT_USERNAME=admin \
            -e MONGO_INITDB_ROOT_PASSWORD=password \
            mongo:6.0
          sleep 10 # Даем время MongoDB запуститься

      # Тесты бэкенда с подключением к MongoDB
      - name: Run backend tests
        run: |
          cd server
          docker build \
            --target test \
            -t backend-test \
            .
          docker run --rm \
            --name backend-test-container \
            --link mongo-test:mongo-test \
            -e MONGO_URI="mongodb://admin:password@mongo-test:27017/subscriptions_test?authSource=admin" \
            backend-test

      # Тесты фронтенда
      - name: Run frontend tests
        run: |
          cd client
          docker build \
            -t $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND_TEST \
            -f Dockerfile.test \
            .
          docker run --rm $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND_TEST

  push:
    needs: [build, test]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push backend image
        run: |
          docker push $DOCKER_HUB_REPO/$IMAGE_NAME_BACKEND

      - name: Push frontend image
        run: |
          docker push $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND