name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_HUB_REPO: andrey122333  # Репозиторий на Docker Hub
  IMAGE_NAME_BACKEND: sub-server:dev  # Основной бэкенд образ (dev)
  IMAGE_NAME_FRONTEND: sub-nginx:latest  # Фронтенд образ
  IMAGE_NAME_BACKEND_TEST: sub-server:test  # Образ для тестов бэка
  IMAGE_NAME_FRONTEND_TEST: sub-client:test  # Образ для тестов фронта
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend
        run: |
          docker build -t $DOCKER_HUB_REPO/$IMAGE_NAME_BACKEND -f server/Dockerfile .

      - name: Build frontend
        run: |
          docker build -t $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND -f client/Dockerfile.nginx .

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Run backend tests (локальный Dockerfile)
        run: |
          docker build -t $DOCKER_HUB_REPO/$IMAGE_NAME_BACKEND_TEST -f server/Dockerfile .
          docker run --rm $DOCKER_HUB_REPO/$IMAGE_NAME_BACKEND_TEST npm test

      - name: Run frontend tests (локальный Dockerfile)
        run: |
          docker build -t $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND_TEST -f client/Dockerfile.test .
          docker run --rm $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND_TEST npm run test

  push:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push backend image
        run: |
          docker push $DOCKER_HUB_REPO/$IMAGE_NAME_BACKEND

      - name: Push frontend image
        run: |
          docker push $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND
