name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - newLaba3
  pull_request:
    branches:
      - newLaba3

env:
  DOCKER_HUB_REPO: andrey122333
  IMAGE_NAME_BACKEND: sub-server:dev
  IMAGE_NAME_FRONTEND: sub-nginx:latest
  IMAGE_NAME_FRONTEND_TEST: sub-client:test

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      backend-digest: ${{ steps.backend-digest.outputs.digest }}
      frontend-digest: ${{ steps.frontend-digest.outputs.digest }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Сборка и сохранение бэкенд образа
      - name: Build and save backend image
        id: build-backend
        run: |
          cd server
          docker build \
            --target dev \
            -t $DOCKER_HUB_REPO/$IMAGE_NAME_BACKEND \
            .
          docker save $DOCKER_HUB_REPO/$IMAGE_NAME_BACKEND -o backend-image.tar
        env:
          DOCKER_HUB_REPO: ${{ env.DOCKER_HUB_REPO }}
          IMAGE_NAME_BACKEND: ${{ env.IMAGE_NAME_BACKEND }}

      - name: Get backend image digest
        id: backend-digest
        run: echo "digest=$(docker inspect --format='{{.Id}}' $DOCKER_HUB_REPO/$IMAGE_NAME_BACKEND)" >> $GITHUB_OUTPUT

      # Сборка и сохранение фронтенд образа
      - name: Build and save frontend image
        id: build-frontend
        run: |
          cd client
          docker build \
            -t $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND \
            -f Dockerfile.nginx \
            .
          docker save $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND -o frontend-image.tar
        env:
          DOCKER_HUB_REPO: ${{ env.DOCKER_HUB_REPO }}
          IMAGE_NAME_FRONTEND: ${{ env.IMAGE_NAME_FRONTEND }}

      - name: Get frontend image digest
        id: frontend-digest
        run: echo "digest=$(docker inspect --format='{{.Id}}' $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND)" >> $GITHUB_OUTPUT

      # Сохранение образов как артефактов
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-images
          path: |
            backend-image.tar
            frontend-image.tar

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Загрузка образов
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: docker-images
          path: .

      - name: Load backend image
        run: docker load -i backend-image.tar

      - name: Load frontend image
        run: docker load -i frontend-image.tar

      # Запуск тестовой MongoDB
      - name: Start MongoDB for backend tests
        run: |
          docker run -d --name mongo-test \
            -p 27038:27017 \
            -e MONGO_INITDB_ROOT_USERNAME=admin \
            -e MONGO_INITDB_ROOT_PASSWORD=password \
            mongo:6.0
          
          # Ожидание готовности MongoDB
          for i in {1..30}; do
            if docker run --rm --network container:mongo-test mongo:6.0 \
              mongo --eval 'db.runCommand("ping").ok' --quiet; then
              break
            fi
            sleep 1
          done

      # Тесты бэкенда
      - name: Run backend tests
        run: |
          cd server
          docker build --target test -t backend-test .
          docker run --rm \
            --name backend-test-container \
            --link mongo-test:mongo-test \
            -e MONGO_URI="mongodb://admin:password@mongo-test:27017/subscriptions_test?authSource=admin" \
            backend-test

      # Тесты фронтенда
      - name: Run frontend tests
        run: |
          cd client
          docker build -t $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND_TEST -f Dockerfile.test .
          docker run --rm $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND_TEST

      - name: Cleanup after tests
        if: always()
        run: |
          docker stop mongo-test || true
          docker rm mongo-test || true

  push:
    needs: [build, test]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: docker-images
          path: .

      - name: Load backend image
        run: docker load -i backend-image.tar

      - name: Load frontend image
        run: docker load -i frontend-image.tar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push backend image
        run: docker push $DOCKER_HUB_REPO/$IMAGE_NAME_BACKEND

      - name: Push frontend image
        run: docker push $DOCKER_HUB_REPO/$IMAGE_NAME_FRONTEND